#!/bin/sh
# see README.md

set -o errexit
set -o nounset
LIB=$(cd $(dirname $0); pwd)

MODULES="bootloader"
#MODULES=`cat brokenlist`

# %s is the module
PRODUCTION_BASE=git://github.com/yast/yast-%s.git
#PRODUCTION_BASE=git@github.com:yast/yast-%s.git
# %s is the module
FIXED_BASE=/var/lib/yast/migration.fixed/yast-%s.git
# the original svn repo:
# SVN_ROOT=https://svn.opensuse.org/svn/yast/
# but I use a local mirror:
SVN_ROOT=file:///dev/shm/REPO

BRANCH_MAP=$LIB/yast-branch-map

for MODULE in $MODULES; do
    PRODUCTION_REPO=`printf $PRODUCTION_BASE $MODULE`
    FIXED_REPO=`printf $FIXED_BASE $MODULE`
    $LIB/recover-repo $PRODUCTION_REPO $FIXED_REPO $SVN_ROOT $MODULE $BRANCH_MAP
done
